server:
  port: 8090

spring:
  application:
    name: msgateway
  cloud:
    gateway:
      routes:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
        web:
          server: trace

eureka:
  client:
    service-url:
      default-zone: http:localhost:8761/eureka

app:
  jwtSecret: 9a02115a835ee03d5fb83cd8a468ea33e4090aaaec87f53c9fa54512bbef4db8dc656c82a315fa0c785c08b0134716b81ddcd0153d2a7556f2e154912cf5675f