spring:
  application:
    name: config
  jackson:
    serialization:
      indent-output: true

server:
  servlet:
    context-path: /config
  port: 8888

eureka:
  client:
    service-url:
      default-zone: http:localhost:8761/eureka

logging:
  level:
    org:
      springframework:
        cloud:
          config:
            server: trace

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true