server:
  port: 8761

spring:
  jackson:
    serialization:
      indent-output: true
  application:
    name: msdiscovery

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

